const test=require("node:test");
const assert=require("node:assert/strict");
const {categories,normalizeCategory,labelFor,categoryOf,withCategory}=require("../workout-categories.js");
test("all app categories have one canonical id and label",()=>{assert.deepEqual(categories.map(x=>x.id),["push","pull","fullbody","crosstrening","kroppsvekt","tabata","core","morgen","toying","nodokt"]);categories.forEach(category=>{assert.equal(normalizeCategory(category.id),category.id);assert.equal(labelFor(category.id),category.label);});});
test("legacy spellings and casing normalize consistently",()=>{assert.equal(normalizeCategory(" BODYWEIGHT "),"kroppsvekt");assert.equal(normalizeCategory("Tøying"),"toying");assert.equal(normalizeCategory("Cross"),"crosstrening");assert.equal(normalizeCategory("KJERNE"),"core");});
test("favorite follows its original template category by source id",()=>{const originals=[{id:"same-name-a",cat:"push",name:"Lik økt"},{id:"same-name-b",cat:"pull",name:"Lik økt"}];assert.equal(categoryOf({sourceTemplateId:"same-name-a",name:"Lik økt",cat:"pull"},originals),"push");assert.equal(categoryOf({sourceTemplateId:"same-name-b",name:"Lik økt"},originals),"pull");});
test("explicit metadata is retained through persistence and removal",()=>{let stored=[withCategory({id:"favorite-1",name:"Nøytralt navn",category:"core"})];stored=JSON.parse(JSON.stringify(stored));assert.equal(categoryOf(stored[0]),"core");stored=stored.filter(item=>item.id!=="favorite-1");assert.deepEqual(stored,[]);});
test("names do not decide category and unknown values are controlled",()=>{assert.equal(categoryOf({name:"Push",cat:"pull"}),"pull");assert.equal(categoryOf({name:"Push",cat:"ukjent"}),null);assert.equal(categoryOf({}),null);assert.equal(withCategory({name:"Gammel økt"},[],"fullbody").cat,"fullbody");});
test("a workout from every category survives favorite save and reload in the same card",()=>{categories.forEach(({id})=>{const original={id:`template-${id}`,cat:id,name:"Samme navn"};const favorite=withCategory({id:`favorite-${id}`,sourceTemplateId:original.id,name:"Samme navn"},[original]);const reloaded=JSON.parse(JSON.stringify(favorite));assert.equal(categoryOf(reloaded,[original]),id);});});

test("all authored workout metadata uses canonical categories",()=>{const source=require("node:fs").readFileSync(require("node:path").join(__dirname,"..","app.js"),"utf8");const authored=[...source.matchAll(/\bcat:"([^"]+)"/g)].map(match=>match[1]);assert.ok(authored.length>0);assert.deepEqual([...new Set(authored.filter(value=>!normalizeCategory(value)))],[]);categories.forEach(({id})=>assert.ok(authored.includes(id),`missing authored workout for ${id}`));});
